import { useTranslation } from 'react-i18next';
import { cn } from '#app/lib/utils';

export interface EntryUnavailableProps {
  className?: string;
}

/**
 * Shown when an entry id resolves to nothing.
 *
 * A missing entry is an ordinary event: ids are permanent and public, so old
 * links, typos, and hand-edited URLs all land here. The reader gets one warm
 * line and a way forward, never an error page.
 *
 * The copy lives in `app/locales/*` and is generated by the wordsmith CLI. Do
 * not inline a string here, and do not hand-edit the locale files.
 */
export function EntryUnavailable({ className }: EntryUnavailableProps) {
  const { t } = useTranslation();

  return (
    <output
      className={cn(
        'block rounded-lg border border-border bg-muted/40 px-4 py-3 text-sm text-muted-foreground',
        className,
      )}
    >
      {t('entry.unavailable.missing')}
    </output>
  );
}
