CREATE TABLE "enrichments" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"sense_id" uuid NOT NULL,
	"headword_id" uuid NOT NULL,
	"from_language_code" text NOT NULL,
	"to_language_code" text NOT NULL,
	"provider" text NOT NULL,
	"model" text NOT NULL,
	"prompt_version" integer NOT NULL,
	"status" text NOT NULL,
	"output" jsonb,
	"error" text,
	"cost_usd" numeric(10, 6),
	"latency_ms" integer NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "enrichments_status_check" CHECK (status in ('ok', 'failed'))
);
--> statement-breakpoint
ALTER TABLE "enrichments" ADD CONSTRAINT "enrichments_sense_id_senses_id_fk" FOREIGN KEY ("sense_id") REFERENCES "public"."senses"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "enrichments" ADD CONSTRAINT "enrichments_headword_id_headwords_id_fk" FOREIGN KEY ("headword_id") REFERENCES "public"."headwords"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "enrichments" ADD CONSTRAINT "enrichments_from_language_code_languages_code_fk" FOREIGN KEY ("from_language_code") REFERENCES "public"."languages"("code") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "enrichments" ADD CONSTRAINT "enrichments_to_language_code_languages_code_fk" FOREIGN KEY ("to_language_code") REFERENCES "public"."languages"("code") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "enrichments_ok_cache_key_unique" ON "enrichments" USING btree ("sense_id","from_language_code","to_language_code","model","prompt_version") WHERE "status" = 'ok';--> statement-breakpoint
CREATE INDEX "enrichments_lookup_idx" ON "enrichments" USING btree ("headword_id","from_language_code","to_language_code","model","prompt_version");--> statement-breakpoint
-- The provenance row for our own enrichment output, seeded here for the same
-- reason the four `languages` rows are seeded in 0001: it is reference data the
-- application must be able to assume, not something a runtime path invents.
-- `LLM-GENERATED` is already on the served allowlist in
-- app/lib/dictionary/licences.ts, and it is its own licence precisely so that
-- generated text stays distinguishable from imported text at every layer.
-- The attribution names no single model, because the model that produced a row
-- is recorded on the row itself and changes whenever a superadmin switches it.
INSERT INTO "sources" ("slug", "name", "url", "licence", "attribution") VALUES
	('llm-generated', 'Generated explanations', NULL, 'LLM-GENERATED', 'Generated by a language model, unreviewed by a person.')
ON CONFLICT ("slug") DO NOTHING;
