import { eq } from 'drizzle-orm';
import type { DataMigrationDb } from '../runner';
import { GENERATED_SOURCE_SLUG } from '#app/lib/dictionary/generated-source';
import { sources } from '#drizzle/schema';

/**
 * Move the generated-content source row onto CC0, with a name and an
 * attribution a reader can actually act on.
 *
 * WHICH ROW
 *   `sources` where `slug = 'llm-generated'`, the one row every generated
 *   headword, sense, sense version and translation attributes to. The slug is
 *   read from `GENERATED_SOURCE_SLUG` below rather than typed again, so the
 *   migration and the code that writes under it cannot name two different rows.
 *
 * WHY THIS EXISTS
 *   The row has sat in `sources` since the first migration, attached to zero
 *   headwords, senses and translations, holding a name that described a feature
 *   that never wrote a row (`Generated explanations`), a licence identifier of
 *   its own invention, and an attribution string that said nothing. The
 *   translation job now writes real dictionary rows under it, so all three
 *   fields become reader-facing at once and all three have to be right before
 *   the first row lands.
 *
 *   `licence` becomes `CC0-1.0`, which is the operator decision of 2026-09-05:
 *   generated entries are released under CC0 like the imported data. That value
 *   is already on the served allowlist, so nothing about servability changes.
 *
 *   `name` becomes a generic label. It deliberately does NOT name a model. The
 *   active model is an operator setting that changes while the service runs, so
 *   a model id in this column would be a claim about rows written under a
 *   different one. The model and the prompt version of each run live on the
 *   `translation_runs` row instead, which is written per run and cannot go
 *   stale.
 *
 *   `url` gets the CC0 deed, so the attribution card's licence line has
 *   somewhere to point.
 *
 * WHAT DEPENDS ON IT
 *   `app/routes/attribution.tsx` renders this row's card, found by SLUG. It used
 *   to be found by its licence string, which this migration changes, and that is
 *   why the page and this file moved in the same change: the old wiring would
 *   have matched nothing and the generated source would have rendered beside
 *   Wikidata as though it were an import.
 *
 * IDEMPOTENT
 *   A plain UPDATE to fixed values. A second run writes the same four fields and
 *   changes nothing. The runner also records the name in `data_migrations` and
 *   will not call this again in the same environment; the idempotence is the belt
 *   to that brace, and it is what makes it safe to run by hand against a database
 *   restored from a dump.
 *
 * `imported_at` AND `version` ARE LEFT ALONE, both null. This source is not an
 * import: there is no upstream dump and no release tag, and the attribution card
 * already renders "not imported" for a null. Writing today's date there would be
 * a lie in a column readers are shown.
 */
export default async function (db: DataMigrationDb): Promise<void> {
  await db
    .update(sources)
    .set({
      name: 'Generated entries',
      licence: 'CC0-1.0',
      url: 'https://creativecommons.org/publicdomain/zero/1.0/',
      attribution:
        "Generated by a language model at a reader's request. Released under CC0 1.0, like the imported data.",
    })
    .where(eq(sources.slug, GENERATED_SOURCE_SLUG));
}
