/**
 * The two mail templates, rendered against the REAL catalogs.
 *
 * The catalogs are read off disk rather than imported, for the same reason
 * `i18n-locales.test.ts` reads them: this test must fail when a translation
 * run drops a key, and a test that renders its own fixture strings cannot.
 *
 * What is asserted is structure, never wording. The German is generated by the
 * workspace `wordsmith` CLI, so pinning a sentence here would read a
 * legitimate re-run as a regression and the next person would edit the test
 * instead of the copy.
 */
import { describe, it } from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

import { verifyEmailTemplate } from '../../../app/emails/verify-email';
import { resetPasswordTemplate } from '../../../app/emails/reset-password';

const REPO_ROOT = fileURLToPath(new URL('../../../', import.meta.url));

/** The languages the app ships mail in. */
const LANGUAGES = ['en', 'de'] as const;

/** The parts every mail is built from, in the order the body carries them. */
const PARTS = ['greeting', 'body', 'action', 'ignore', 'signoff'] as const;

/** A stand-in link, distinctive enough to count occurrences of. Not named `URL`, which is a global here. */
const LINK = 'https://kenning.altan.fyi/verify?token=abc123';

/** Written as escapes so this file does not trip `design-rules.test.ts` itself. */
const DASHES = ['-', '–', '—'];

/** A catalog node: nested objects bottoming out in strings. */
type Catalog = { [key: string]: string | Catalog };

function loadCatalog(language: string): Catalog {
  const raw = readFileSync(`${REPO_ROOT}app/locales/${language}/common.json`, 'utf8');
  const parsed: Catalog = JSON.parse(raw);
  assert.ok(parsed instanceof Object, `${language} catalog is not an object`);
  return parsed;
}

/**
 * The one call shape the templates make, backed by the real catalog. Passing
 * this rather than an i18next instance keeps the test free of i18next's own
 * initialisation, which is not what is under test here.
 */
function makeTranslator(catalog: Catalog): (key: string) => string {
  return (key) => {
    let node: string | Catalog | undefined = catalog;
    for (const part of key.split('.')) {
      if (node === undefined || !(node instanceof Object)) return key;
      node = node[part];
    }
    return node instanceof Object || node === undefined ? key : node;
  };
}

function countOccurrences(haystack: string, needle: string): number {
  return haystack.split(needle).length - 1;
}

/** The body without the link line, which legitimately carries a hyphen. */
function bodyWithoutLink(text: string): string {
  return text
    .split('\n')
    .filter((line) => line !== LINK)
    .join('\n');
}

describe('mail templates', () => {
  for (const language of LANGUAGES) {
    const t = makeTranslator(loadCatalog(language));

    const cases = [
      { name: 'verify', namespace: 'email.verify', rendered: verifyEmailTemplate(t, { url: LINK }) },
      { name: 'reset', namespace: 'email.reset', rendered: resetPasswordTemplate(t, { url: LINK }) },
    ];

    for (const { name, namespace, rendered } of cases) {
      it(`renders the ${name} mail in ${language} from the catalog`, () => {
        assert.notEqual(rendered.subject, `${namespace}.subject`, 'subject key is missing from the catalog');
        assert.ok(rendered.subject.length > 0);

        for (const part of PARTS) {
          const key = `${namespace}.${part}`;
          const value = t(key);
          assert.notEqual(value, key, `${key} is missing from the ${language} catalog`);
          assert.ok(rendered.text.includes(value), `${key} is missing from the ${language} body`);
        }
      });

      it(`puts the link on its own line exactly once in the ${name} mail in ${language}`, () => {
        assert.equal(countOccurrences(rendered.text, LINK), 1);
        assert.ok(rendered.text.split('\n').includes(LINK), 'the link shares a line with other text');
        assert.ok(rendered.text.includes(`\n\n${LINK}\n\n`), 'the link is not set off by blank lines');
      });

      it(`writes the ${name} mail in ${language} without a dash character`, () => {
        const prose = `${rendered.subject}\n${bodyWithoutLink(rendered.text)}`;
        for (const dash of DASHES) {
          assert.ok(!prose.includes(dash), `the ${language} ${name} mail contains ${JSON.stringify(dash)}`);
        }
      });

      it(`names no product or service in the ${name} mail in ${language}`, () => {
        const prose = `${rendered.subject} ${bodyWithoutLink(rendered.text)}`.toLowerCase();
        for (const forbidden of ['kenning.altan.fyi', 'pigeon', 'sparq']) {
          assert.ok(!prose.includes(forbidden), `the mail names ${forbidden}`);
        }
      });
    }
  }
});
