/**
 * Structural guard for the UI translation catalogs under `app/locales/`.
 *
 * These files are GENERATED by the workspace `wordsmith` CLI
 * (`pnpm -C djinn wordsmith`). Nobody writes or edits them by hand, so a test
 * pinned to a German sentence would read a perfectly legitimate re-run as a
 * regression, and the next person would fix the test instead of the copy. This
 * test therefore asserts STRUCTURE and never wording: the same key set in every
 * locale, a non-empty string at every leaf, the same `{{placeholder}}` set on
 * both sides of a translation, and no em dash anywhere in a value.
 *
 * Those are exactly the failures a translation run can introduce silently. A
 * dropped key renders a raw dotted path on screen, a swallowed placeholder
 * renders a sentence with a hole in it, and neither shows up in a typecheck.
 *
 * The locales are discovered by reading `app/locales/` rather than from a
 * hardcoded pair, so a third language is covered the day it is added. Every
 * violation is collected and reported together with its dotted key path.
 */
import { describe, it } from 'node:test';
import assert from 'node:assert/strict';
import { readdirSync, readFileSync } from 'node:fs';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { z } from 'zod';

import type { JsonObject, JsonValue } from '../../app/lib/json';

const REPO_ROOT = fileURLToPath(new URL('../../', import.meta.url));
const LOCALES_DIRECTORY = 'app/locales';

/** The catalog every other locale is measured against. */
const REFERENCE_LOCALE = 'en';

/** Locales the app ships today. A missing one is a packaging bug, not a new language. */
const REQUIRED_LOCALES = ['en', 'de'];

/** Written as an escape on purpose, so this file does not trip `design-rules.test.ts`. */
const EM_DASH = '\u2014';

/** i18next interpolation, the only dynamic form these catalogs use: `{{count}}`. */
const PLACEHOLDER = /\{\{\s*([^{}]+?)\s*\}\}/g;

/**
 * The catalogs are JSON, so the shape is decoded with a schema rather than
 * inspected with runtime `typeof` checks. `z.lazy` carries the recursion.
 */
const LocaleValueSchema: z.ZodType<JsonValue> = z.lazy(() =>
  z.union([
    z.string(),
    z.number(),
    z.boolean(),
    z.null(),
    z.array(LocaleValueSchema),
    z.record(z.string(), LocaleValueSchema),
  ]),
);
const LocaleTreeSchema: z.ZodType<JsonObject> = z.record(z.string(), LocaleValueSchema);
const LocaleArraySchema = z.array(LocaleValueSchema);
const LeafSchema = z.string();

/** One catalog, flattened to dotted keys, plus whatever went wrong reading it. */
type Catalog = {
  locale: string;
  file: string;
  values: Map<string, string>;
  problems: string[];
};

/** How a locale's key set differs from the reference locale's. */
type KeyDiff = {
  missing: string[];
  extra: string[];
};

function flatten(tree: JsonObject, prefix: string, values: Map<string, string>, problems: string[]): void {
  for (const [key, value] of Object.entries(tree)) {
    const path = prefix === '' ? key : `${prefix}.${key}`;

    // An array leaf would flatten into numeric keys and read as a branch, so it
    // is rejected explicitly. These catalogs hold objects and strings only.
    if (LocaleArraySchema.safeParse(value).success) {
      problems.push(`${path}: arrays are not allowed in a catalog`);
      continue;
    }

    const branch = LocaleTreeSchema.safeParse(value);
    if (branch.success) {
      flatten(branch.data, path, values, problems);
      continue;
    }

    const leaf = LeafSchema.safeParse(value);
    if (!leaf.success) {
      problems.push(`${path}: expected a string, found ${JSON.stringify(value)}`);
      continue;
    }
    if (leaf.data.trim() === '') {
      problems.push(`${path}: empty string`);
      continue;
    }
    values.set(path, leaf.data);
  }
}

function readCatalog(locale: string): Catalog {
  const file = `${LOCALES_DIRECTORY}/${locale}/common.json`;
  const values = new Map<string, string>();
  const problems: string[] = [];

  const source = readFileSync(join(REPO_ROOT, file), 'utf8');
  const decoded = LocaleTreeSchema.safeParse(JSON.parse(source));
  if (!decoded.success) {
    problems.push(`${file}: not a JSON object (${decoded.error.issues[0]?.message ?? 'unknown reason'})`);
    return { locale, file, values, problems };
  }

  flatten(decoded.data, '', values, problems);
  return { locale, file, values, problems };
}

/** The symmetric difference of two flattened catalogs, reported both ways round. */
function diffKeys(reference: ReadonlyMap<string, string>, other: ReadonlyMap<string, string>): KeyDiff {
  return {
    missing: [...reference.keys()].filter((key) => !other.has(key)).toSorted(),
    extra: [...other.keys()].filter((key) => !reference.has(key)).toSorted(),
  };
}

function placeholdersIn(value: string): string[] {
  return [...value.matchAll(PLACEHOLDER)].map((match) => match[1] ?? '').toSorted();
}

const locales = readdirSync(join(REPO_ROOT, LOCALES_DIRECTORY), { withFileTypes: true })
  .filter((entry) => entry.isDirectory())
  .map((entry) => entry.name)
  .toSorted();

const catalogs = new Map(locales.map((locale) => [locale, readCatalog(locale)]));

function catalogFor(locale: string): Catalog {
  const catalog = catalogs.get(locale);
  if (!catalog) throw new Error(`no catalog read for locale "${locale}"`);
  return catalog;
}

describe('i18n locale catalogs', () => {
  it('discovers the shipped locales and reads a non-trivial catalog', () => {
    for (const required of REQUIRED_LOCALES) {
      assert.ok(locales.includes(required), `expected a "${required}" locale directory, found: ${locales.join(', ')}`);
    }
    // A discovery that reads nothing would pass every assertion below.
    const reference = catalogFor(REFERENCE_LOCALE);
    assert.ok(
      reference.values.size >= 20,
      `expected at least 20 keys in ${reference.file}, flattened ${reference.values.size}`,
    );
  });

  it('holds a non-empty string at every leaf, in every locale', () => {
    const problems = locales.flatMap((locale) => catalogFor(locale).problems);
    assert.deepEqual(problems, [], `Every catalog leaf must be a non-empty string.\n  ${problems.join('\n  ')}`);
  });

  it(`has the same key set as ${REFERENCE_LOCALE} in every locale`, () => {
    const reference = catalogFor(REFERENCE_LOCALE);
    const failures: string[] = [];

    for (const locale of locales) {
      if (locale === REFERENCE_LOCALE) continue;
      const catalog = catalogFor(locale);
      const { missing, extra } = diffKeys(reference.values, catalog.values);
      if (missing.length === 0 && extra.length === 0) continue;
      failures.push(
        [
          `${catalog.file} does not match ${reference.file}:`,
          `  missing from ${locale} (${missing.length}): ${missing.join(', ') || 'none'}`,
          `  present only in ${locale} (${extra.length}): ${extra.join(', ') || 'none'}`,
        ].join('\n'),
      );
    }

    assert.deepEqual(failures, [], `Locale key sets diverged.\n${failures.join('\n')}`);
  });

  it('uses no em dash in any value', () => {
    const hits: string[] = [];
    for (const locale of locales) {
      const catalog = catalogFor(locale);
      for (const [key, value] of catalog.values) {
        if (!value.includes(EM_DASH)) continue;
        hits.push(`${catalog.file} ${key}: ${value}`);
      }
    }
    assert.deepEqual(hits, [], `Never use em dashes in copy, use a comma instead.\n  ${hits.join('\n  ')}`);
  });

  it(`keeps the same {{placeholders}} as ${REFERENCE_LOCALE} in every locale`, () => {
    const reference = catalogFor(REFERENCE_LOCALE);
    const hits: string[] = [];

    for (const locale of locales) {
      if (locale === REFERENCE_LOCALE) continue;
      const catalog = catalogFor(locale);
      // Only keys present on both sides, a key set mismatch is its own test.
      for (const [key, referenceValue] of reference.values) {
        const translated = catalog.values.get(key);
        if (translated === undefined) continue;
        const expected = placeholdersIn(referenceValue);
        const actual = placeholdersIn(translated);
        if (expected.join('|') === actual.join('|')) continue;
        hits.push(`${catalog.file} ${key}: expected ${JSON.stringify(expected)}, found ${JSON.stringify(actual)}`);
      }
    }

    assert.deepEqual(hits, [], `A translation changed an interpolation placeholder.\n  ${hits.join('\n  ')}`);
  });

  it('reports the symmetric difference, both ways round (guards the comparison itself)', () => {
    // The real catalogs are in sync, so this comparison can only be proven to
    // discriminate on synthetic input. Without it the test above is vacuous.
    const reference = new Map([
      ['nav.search', 'Search'],
      ['nav.lists', 'Lists'],
    ]);
    const translated = new Map([
      ['nav.search', 'Suche'],
      ['nav.leftovers', 'Reste'],
    ]);
    assert.deepEqual(diffKeys(reference, translated), { missing: ['nav.lists'], extra: ['nav.leftovers'] });
    assert.deepEqual(diffKeys(reference, reference), { missing: [], extra: [] });
  });

  it('rejects a null, a number and an empty leaf (guards the flattener)', () => {
    const values = new Map<string, string>();
    const problems: string[] = [];
    flatten(
      { good: 'Search', missing: null, count: 3, blank: '   ', nested: { deep: 'Lists' }, list: ['a'] },
      '',
      values,
      problems,
    );
    assert.deepEqual(
      [...values.entries()],
      [
        ['good', 'Search'],
        ['nested.deep', 'Lists'],
      ],
    );
    assert.deepEqual(problems.toSorted(), [
      'blank: empty string',
      'count: expected a string, found 3',
      'list: arrays are not allowed in a catalog',
      'missing: expected a string, found null',
    ]);
  });

  it('detects a dropped placeholder (guards the comparison itself)', () => {
    // There may be zero placeholders in the catalogs today. The comparison still
    // has to be proven to discriminate, or it passes vacuously forever.
    assert.deepEqual(placeholdersIn('Found {{count}} results for {{ query }}'), ['count', 'query']);
    assert.deepEqual(placeholdersIn('Keine Ergebnisse'), []);
  });
});
